branch_name='origin/folsom'
mod 'CiscoSystems/apache', :git =>'git://github.com/CiscoSystems/puppet-apache', :ref => branch_name
mod 'CiscoSystems/apt', :git =>'git://github.com/CiscoSystems/puppet-apt', :ref => branch_name
mod 'CiscoSystems/apt-cacher-ng', :git =>'git://github.com/CiscoSystems/puppet-apt-cacher-ng', :ref => branch_name
mod 'CiscoSystems/cobbler', :git =>'git://github.com/bodepd/puppet-cobbler', :ref => 'origin/fix_cobbler_sync_issue'
mod 'CiscoSystems/coe', :git =>'git://github.com/CiscoSystems/puppet-coe', :ref => branch_name
mod 'CiscoSystems/collectd', :git =>'git://github.com/CiscoSystems/puppet-collectd', :ref => branch_name
mod 'CiscoSystems/concat', :git =>'git://github.com/CiscoSystems/puppet-concat', :ref => branch_name
mod 'CiscoSystems/corosync', :git =>'git://github.com/CiscoSystems/puppet-corosync', :ref => branch_name
mod 'CiscoSystems/dnsmasq', :git =>'git://github.com/CiscoSystems/puppet-dnsmasq', :ref => branch_name
mod 'CiscoSystems/drbd', :git =>'git://github.com/CiscoSystems/puppet-drbd', :ref => branch_name
mod 'CiscoSystems/glance', :git =>'git://github.com/CiscoSystems/puppet-glance', :ref => branch_name
mod 'CiscoSystems/graphite', :git =>'git://github.com/CiscoSystems/puppet-graphite', :ref => branch_name
mod 'CiscoSystems/horizon', :git =>'git://github.com/CiscoSystems/puppet-horizon', :ref => branch_name
mod 'CiscoSystems/inifile', :git =>'git://github.com/CiscoSystems/puppet-inifile', :ref => branch_name
mod 'CiscoSystems/keystone', :git =>'git://github.com/CiscoSystems/puppet-keystone', :ref => branch_name
mod 'CiscoSystems/memcached', :git =>'git://github.com/CiscoSystems/puppet-memcached', :ref => branch_name
mod 'CiscoSystems/monit', :git =>'git://github.com/CiscoSystems/puppet-monit', :ref => branch_name
mod 'CiscoSystems/mysql', :git =>'git://github.com/CiscoSystems/puppet-mysql', :ref => branch_name
mod 'CiscoSystems/naginator', :git =>'git://github.com/CiscoSystems/puppet-naginator', :ref => branch_name
mod 'CiscoSystems/nova', :git =>'git://github.com/CiscoSystems/puppet-nova', :ref => branch_name
mod 'CiscoSystems/ntp', :git =>'git://github.com/CiscoSystems/puppet-ntp', :ref => branch_name
mod 'CiscoSystems/openstack', :git =>'git://github.com/CiscoSystems/puppet-openstack', :ref => branch_name
mod 'CiscoSystems/openstack_admin', :git =>'git://github.com/CiscoSystems/puppet-openstack_admin', :ref => branch_name
mod 'CiscoSystems/pip', :git =>'git://github.com/CiscoSystems/puppet-pip', :ref => branch_name
mod 'CiscoSystems/puppet', :git =>'git://github.com/CiscoSystems/puppet-puppet', :ref => branch_name
mod 'CiscoSystems/quantum', :git =>'git://github.com/CiscoSystems/puppet-quantum', :ref => branch_name
mod 'CiscoSystems/rabbitmq', :git =>'git://github.com/CiscoSystems/puppet-rabbitmq', :ref => branch_name
mod 'CiscoSystems/rsync', :git =>'git://github.com/CiscoSystems/puppet-rsync', :ref => branch_name
mod 'CiscoSystems/stdlib', :git =>'git://github.com/CiscoSystems/puppet-stdlib', :ref => branch_name
#mod 'CiscoSystems/swift', :git =>'git://github.com/CiscoSystems/puppet-swift', :ref => branch_name
mod 'CiscoSystems/sysctl', :git =>'git://github.com/CiscoSystems/puppet-sysctl', :ref => branch_name
mod 'CiscoSystems/vswitch', :git =>'git://github.com/CiscoSystems/puppet-vswitch', :ref => branch_name
mod 'CiscoSystems/xinetd', :git =>'git://github.com/CiscoSystems/puppet-xinetd', :ref => branch_name
mod 'CiscoSystems/ssh', :git =>'git://github.com/CiscoSystems/puppet-ssh', :ref => branch_name
